[package]
name = "probabilistic-set"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = { workspace = true }
serde = { workspace = true, features = ["derive"] }
speedy = { workspace = true }

[dev-dependencies]
uuid = { version = "1.0", features = ["v4"] }

[lints]
workspace = true
