steps:
  - label: "🔨 Build Corrosion and Workload"
    priority: 70
    key: build-corrosion
    commands:
      - docker build -f .antithesis/corrosion/Dockerfile -t corrosion .
      - docker tag corrosion -t ${ANTITHEIS_REGISTRY}/corrosion:${BUILDKITE_COMMIT} .
      - docker push ${ANTITHEIS_REGISTRY}/corrosion:${BUILDKITE_COMMIT}
      # client image is built from corrosion image
      - docker build -f .antithesis/client/Dockerfile -t ${ANTITHEIS_REGISTRY}/corro-client:${BUILDKITE_COMMIT} .
      - docker push ${ANTITHEIS_REGISTRY}/corro-client:${BUILDKITE_COMMIT}
    plugins:
      - docker-login#v3.0.0:
          username: _json_key
          password-env: ANTITHEIS_REGISTRY_PASSWORD
          server: https://us-central1-docker.pkg.dev
    agents:
      queue: "high-concurrency"

  - label: "🔨 Build Config"
    priority: 70
    key: build-config
    commands:
      - envsubst < .antithesis/config/docker-compose.yaml.tmpl > .antithesis/config/docker-compose.yaml
      - docker build -f .antithesis/Dockerfile -t ${ANTITHEIS_REGISTRY}/antithesis-config:${BUILDKITE_COMMIT} .
      - docker push ${ANTITHEIS_REGISTRY}/antithesis-config:${BUILDKITE_COMMIT}
    plugins:
      - docker-login#v3.0.0::
          username: _json_key
          password-env: ANTITHEIS_REGISTRY_PASSWORD
    agents:
      queue: "high-concurrency"
    depends_on: [build-corrosion, build-client]

  - label: "☁️ Test on Antithesis"
    priority: 50
    key: deploy
    commands:
      - .buildkite-corro_antithesis/test.sh
    depends_on: [build-config]
