CREATE TABLE todos (
    id BLOB NOT NULL PRIMARY KEY,
    title TEXT NOT NULL DEFAULT '',
    completed_at INTEGER
);

CREATE TABLE IF NOT EXISTS tests (
    id INTEGER NOT NULL PRIMARY KEY,
    text TEXT NOT NULL DEFAULT ""
) WITHOUT ROWID;

CREATE TABLE IF NOT EXISTS tests2 (
    id INTEGER NOT NULL PRIMARY KEY,
    text TEXT NOT NULL DEFAULT ""
) WITHOUT ROWID;

CREATE TABLE IF NOT EXISTS tests3 (
    id INTEGER NOT NULL PRIMARY KEY,
    text TEXT NOT NULL DEFAULT "",
    text2 TEXT NOT NULL DEFAULT "",
    num INTEGER NOT NULL DEFAULT 0,
    num2 INTEGER NOT NULL DEFAULT 0
) WITHOUT ROWID;

CREATE TABLE IF NOT EXISTS testsblob (
    id BLOB NOT NULL PRIMARY KEY,
    text TEXT NOT NULL DEFAULT ""
) WITHOUT ROWID;

CREATE TABLE IF NOT EXISTS testsbool (
    id INTEGER NOT NULL PRIMARY KEY,
    b boolean not null default false
);

CREATE TABLE IF NOT EXISTS wide (
    id1 BLOB NOT NULL,
    id2 TEXT NOT NULL,

    int INTEGER NOT NULL DEFAULT 1,
    float REAL NOT NULL DEFAULT 1.0,

    blob BLOB,

    PRIMARY KEY (id1, id2)
);
