[db]
path = "/var/lib/corrosion/state.db"
schema_paths = ["/etc/corrosion/schemas"]
    
[gossip]
# addr and bootstrap for Fly.io deployment example are written 
# on startup by entrypoint script
plaintext = true
max_mtu = 1372
disable_gso = true

[api]
addr = "[::]:8080"
# authz = { bearer-token = "secure-token" }

[admin]
path = "/app/admin.sock"

[telemetry]
prometheus.addr = "0.0.0.0:9090"

[log]
colors = false